- name: variables to print
  hosts: web
  vars:   #Variables from Play Level
    COURSE: "DevOps with AWS from PLAY level"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy M"
  vars_files:   #Variables from Files
  - vars.yml
  vars_prompt:   #Variables from Prompt
  - name: COURSE
    prompt: Please enter the course name
    private: false # not confidential
  tasks:
  - name: print the information
    vars:   #Variables from Task Level
      COURSE: "DevOps with AWS from TASK level"
      DURATION: "120HRS"
      TRAINER: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}"

#In any programming language, command-line arguments was the first preference
#1. command line/args
#2. Task level
#3. Files
#4. prompt
#5. Play
#6. inventory
#7. Roles