- name: loops demo-1
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }} "
    loop:
    - Ramesh
    - Suresh
    - Robert
    - Raheem
  

- name: loops demo-2
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present 
    loop:
    - mysql
    - nginx
    - postfix
    - httpd

  
- name: loops demo-3
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}" 
    loop:
    - { name: 'mysql', state: 'present' }
    - { name: 'nginx', state: 'absent' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'nginx', state: 'present' }